[tools]
go = "1.27.0"
node = "24.18.0"
npm = "latest"
sqlc = "1.31.1"

[env]
ENVIRONMENT = "prod"
MACOSX_DEPLOYMENT_TARGET="13.0"
CGO_CFLAGS="-mmacosx-version-min=13.0"
CGO_CXXFLAGS="-mmacosx-version-min=13.0"
CGO_LDFLAGS="-mmacosx-version-min=13.0"

[tasks.dev-app]
description = "开发 APP"
run = "go run ./cmd/app"
env = {
    ENVIRONMENT = "dev",
    NAME = "evo",
    VERSION = "0.0.1",
    DSN = "file:./tmp/data.sqlite"
}
raw = true


[tasks.dev-web]
description = "开发 APP"
run = "npm --prefix ./web run dev"
env = {
}
raw = true



[tasks.build-web]
description = "构建 WEB"
dir = "web"
run = "npm run build"

[tasks.test]
description = "运行所有 TEST"
run = "go test ./..."

[tasks.gen-sqlc]
description = "生成 sqlc 代码"
run = "sqlc generate -f db/sqlc.yml"

[tasks.gen-types]
description = "生成 Wails Bindings 代码"
run = "wails3 generate bindings -ts -i -d ./web/src/types ./cmd/app"