[tools]
go = "1.27.0"
node = "24.18.0"
sqlc = "1.31.1"


[tasks.cli-dev]
description = "开发 CLI"
run = "go run ./cmd/cli"
env = {
    ENVIRONMENT = "dev"
}

[tasks.api-dev]
description = "开发 API"
run = "go run ./cmd/api"
env = {
    ENVIRONMENT = "dev"
}

[env]
ENVIRONMENT = "prod"
