/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Evorsio API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ErrorModel,
  LoginRequestBody,
  LoginResponseBody,
  SendCodeRequestBody,
  SendCodeResponseBody
} from './model';



export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;




export type postAuthLoginResponse200 = {
  data: LoginResponseBody
  status: 200
}

export type postAuthLoginResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type postAuthLoginResponseSuccess = (postAuthLoginResponse200) & {
  headers: Headers;
};
export type postAuthLoginResponseError = (postAuthLoginResponseDefault) & {
  headers: Headers;
};

export type postAuthLoginResponse = (postAuthLoginResponseSuccess | postAuthLoginResponseError)

export const getPostAuthLoginUrl = () => {




  return `/api/auth/login`
}

/**
 * @summary Post auth login
 */
export const postAuthLogin = async (loginRequestBody: LoginRequestBody, options?: RequestInit): Promise<postAuthLoginResponse> => {

  const res = await fetch(getPostAuthLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginRequestBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postAuthLoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postAuthLoginResponse
}





export const getPostAuthLoginMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: LoginRequestBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: LoginRequestBody}, TContext> => {

const mutationKey = ['postAuthLogin'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogin>>, {data: LoginRequestBody}> = (props) => {
          const {data} = props ?? {};

          return  postAuthLogin(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogin>>>
    export type PostAuthLoginMutationBody = LoginRequestBody
    export type PostAuthLoginMutationError = ErrorModel

    /**
 * @summary Post auth login
 */
export const usePostAuthLogin = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: LoginRequestBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogin>>,
        TError,
        {data: LoginRequestBody},
        TContext
      > => {
      return useMutation(getPostAuthLoginMutationOptions(options), queryClient);
    }
    export type postAuthSendCodeResponse200 = {
  data: SendCodeResponseBody
  status: 200
}

export type postAuthSendCodeResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type postAuthSendCodeResponseSuccess = (postAuthSendCodeResponse200) & {
  headers: Headers;
};
export type postAuthSendCodeResponseError = (postAuthSendCodeResponseDefault) & {
  headers: Headers;
};

export type postAuthSendCodeResponse = (postAuthSendCodeResponseSuccess | postAuthSendCodeResponseError)

export const getPostAuthSendCodeUrl = () => {




  return `/api/auth/send-code`
}

/**
 * @summary Post auth send code
 */
export const postAuthSendCode = async (sendCodeRequestBody: SendCodeRequestBody, options?: RequestInit): Promise<postAuthSendCodeResponse> => {

  const res = await fetch(getPostAuthSendCodeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(sendCodeRequestBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postAuthSendCodeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postAuthSendCodeResponse
}





export const getPostAuthSendCodeMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthSendCode>>, TError,{data: SendCodeRequestBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthSendCode>>, TError,{data: SendCodeRequestBody}, TContext> => {

const mutationKey = ['postAuthSendCode'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthSendCode>>, {data: SendCodeRequestBody}> = (props) => {
          const {data} = props ?? {};

          return  postAuthSendCode(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthSendCodeMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthSendCode>>>
    export type PostAuthSendCodeMutationBody = SendCodeRequestBody
    export type PostAuthSendCodeMutationError = ErrorModel

    /**
 * @summary Post auth send code
 */
export const usePostAuthSendCode = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthSendCode>>, TError,{data: SendCodeRequestBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthSendCode>>,
        TError,
        {data: SendCodeRequestBody},
        TContext
      > => {
      return useMutation(getPostAuthSendCodeMutationOptions(options), queryClient);
    }
