services:
  postgres:
    image: postgres:17
    container_name: evorsio-postgres
    environment:
      POSTGRES_DB: evorsio
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
