// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum Kind {
  /**
   * The Go zero value for the underlying type of the enum.
   */
  $zero = "",

  KindDrive = "drive",
  KindVault = "vault",
}
