// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface PageResult<T> {
  Items: T[] | null
  NextCursor: string
  HasMore: boolean
}
