/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Evorsio API
 * OpenAPI spec version: 1.0.0
 */

export interface Health {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  message: string;
}
