/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Evorsio API
 * OpenAPI spec version: 1.0.0
 */

export interface LoginRequestBody {
  /** @pattern ^[0-9]{5}$ */
  code: string;
  /**
     * @minLength 3
     * @maxLength 255
     */
  email: string;
}
