/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Evorsio API
 * OpenAPI spec version: 1.0.0
 */

export interface SendCodeRequestBody {
  /**
     * @minLength 3
     * @maxLength 255
     */
  email: string;
}
