// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drive.sql

package dbgen

import (
	"context"
)

const existsFolderById = `-- name: ExistsFolderById :one
select exists(select 1 from resource where id = ? and type = 'folder')
`

func (q *Queries) ExistsFolderById(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsFolderById, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertEntry = `-- name: InsertEntry :exec
insert into entry (parent_id, child_id) values (?,?)
`

type InsertEntryParams struct {
	ParentID string
	ChildID  string
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertEntry, arg.ParentID, arg.ChildID)
	return err
}

const insertFile = `-- name: InsertFile :exec
insert into file (resource_id, size, mime_type) values (?,?,?)
`

type InsertFileParams struct {
	ResourceID string
	Size       int64
	MimeType   string
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) error {
	_, err := q.db.ExecContext(ctx, insertFile, arg.ResourceID, arg.Size, arg.MimeType)
	return err
}

const insertSymlink = `-- name: InsertSymlink :exec
insert into symlink (resource_id, target_id) values (?,?)
`

type InsertSymlinkParams struct {
	ResourceID string
	TargetID   string
}

func (q *Queries) InsertSymlink(ctx context.Context, arg InsertSymlinkParams) error {
	_, err := q.db.ExecContext(ctx, insertSymlink, arg.ResourceID, arg.TargetID)
	return err
}

const selectChildrenByParentId = `-- name: SelectChildrenByParentId :many
select r.id, r.type, r.name, r.created_at, r.updated_at from entry e
join resource r on r.id = e.child_id
where e.parent_id =?
order by r.updated_at desc
`

type SelectChildrenByParentIdRow struct {
	Resource Resource
}

func (q *Queries) SelectChildrenByParentId(ctx context.Context, parentID string) ([]SelectChildrenByParentIdRow, error) {
	rows, err := q.db.QueryContext(ctx, selectChildrenByParentId, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectChildrenByParentIdRow{}
	for rows.Next() {
		var i SelectChildrenByParentIdRow
		if err := rows.Scan(
			&i.Resource.ID,
			&i.Resource.Type,
			&i.Resource.Name,
			&i.Resource.CreatedAt,
			&i.Resource.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectFileById = `-- name: SelectFileById :one
select
    r.id, r.type, r.name, r.created_at, r.updated_at,
    f.resource_id, f.size, f.mime_type
from file f
         join resource r
                    on r.id = f.resource_id
where r.id = ? and r.type = 'file'
`

type SelectFileByIdRow struct {
	Resource Resource
	File     File
}

func (q *Queries) SelectFileById(ctx context.Context, id string) (SelectFileByIdRow, error) {
	row := q.db.QueryRowContext(ctx, selectFileById, id)
	var i SelectFileByIdRow
	err := row.Scan(
		&i.Resource.ID,
		&i.Resource.Type,
		&i.Resource.Name,
		&i.Resource.CreatedAt,
		&i.Resource.UpdatedAt,
		&i.File.ResourceID,
		&i.File.Size,
		&i.File.MimeType,
	)
	return i, err
}

const selectFolderById = `-- name: SelectFolderById :one
select
    r.id, r.type, r.name, r.created_at, r.updated_at
from resource r where r.id = ? and r.type = 'folder'
`

type SelectFolderByIdRow struct {
	Resource Resource
}

func (q *Queries) SelectFolderById(ctx context.Context, id string) (SelectFolderByIdRow, error) {
	row := q.db.QueryRowContext(ctx, selectFolderById, id)
	var i SelectFolderByIdRow
	err := row.Scan(
		&i.Resource.ID,
		&i.Resource.Type,
		&i.Resource.Name,
		&i.Resource.CreatedAt,
		&i.Resource.UpdatedAt,
	)
	return i, err
}

const selectParentByChildId = `-- name: SelectParentByChildId :one
select r.id, r.type, r.name, r.created_at, r.updated_at from entry e
join resource r on r.id = e.parent_id
where e.child_id = ?
`

type SelectParentByChildIdRow struct {
	Resource Resource
}

func (q *Queries) SelectParentByChildId(ctx context.Context, childID string) (SelectParentByChildIdRow, error) {
	row := q.db.QueryRowContext(ctx, selectParentByChildId, childID)
	var i SelectParentByChildIdRow
	err := row.Scan(
		&i.Resource.ID,
		&i.Resource.Type,
		&i.Resource.Name,
		&i.Resource.CreatedAt,
		&i.Resource.UpdatedAt,
	)
	return i, err
}

const selectSymlinkById = `-- name: SelectSymlinkById :one
select
    r.id, r.type, r.name, r.created_at, r.updated_at,
    s.resource_id, s.target_id
from symlink s
         join resource r
                    on r.id = s.resource_id
where r.id = ? and r.type = 'symlink'
`

type SelectSymlinkByIdRow struct {
	Resource Resource
	Symlink  Symlink
}

func (q *Queries) SelectSymlinkById(ctx context.Context, id string) (SelectSymlinkByIdRow, error) {
	row := q.db.QueryRowContext(ctx, selectSymlinkById, id)
	var i SelectSymlinkByIdRow
	err := row.Scan(
		&i.Resource.ID,
		&i.Resource.Type,
		&i.Resource.Name,
		&i.Resource.CreatedAt,
		&i.Resource.UpdatedAt,
		&i.Symlink.ResourceID,
		&i.Symlink.TargetID,
	)
	return i, err
}

const updateEntryParentByChildId = `-- name: UpdateEntryParentByChildId :exec
update entry set parent_id = ? where child_id = ?
`

type UpdateEntryParentByChildIdParams struct {
	ParentID string
	ChildID  string
}

func (q *Queries) UpdateEntryParentByChildId(ctx context.Context, arg UpdateEntryParentByChildIdParams) error {
	_, err := q.db.ExecContext(ctx, updateEntryParentByChildId, arg.ParentID, arg.ChildID)
	return err
}
