// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
	"time"
)

type Operation struct {
	ID            string
	OperationType string
	ResourceID    string
	OldPath       sql.NullString
	NewPath       sql.NullString
	CreatedAt     time.Time
}

type Resource struct {
	ID        string
	Kind      string
	Path      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
