// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource.sql

package dbgen

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const deleteResourceById = `-- name: DeleteResourceById :execresult
delete from resource where id = ?
`

func (q *Queries) DeleteResourceById(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteResourceById, id)
}

const deleteResourcesByIds = `-- name: DeleteResourcesByIds :execresult
delete from resource where id in (/*SLICE:ids*/?)
`

func (q *Queries) DeleteResourcesByIds(ctx context.Context, ids []string) (sql.Result, error) {
	query := deleteResourcesByIds
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	return q.db.ExecContext(ctx, query, queryParams...)
}

const insertResource = `-- name: InsertResource :exec
insert into resource (id, kind,path, created_at, updated_at) values (?,?,?,?,?)
`

type InsertResourceParams struct {
	ID        string
	Kind      string
	Path      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertResource(ctx context.Context, arg InsertResourceParams) error {
	_, err := q.db.ExecContext(ctx, insertResource,
		arg.ID,
		arg.Kind,
		arg.Path,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const selectResourceById = `-- name: SelectResourceById :one
select id, kind, path, created_at, updated_at from resource where id = ?
`

func (q *Queries) SelectResourceById(ctx context.Context, id string) (Resource, error) {
	row := q.db.QueryRowContext(ctx, selectResourceById, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectResourcesByPath = `-- name: SelectResourcesByPath :many
select id, kind, path, created_at, updated_at from resource where path like '%'||?1 ||'%'
`

func (q *Queries) SelectResourcesByPath(ctx context.Context, path sql.NullString) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, selectResourcesByPath, path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Path,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
