// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource.sql

package dbgen

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const deleteResourceById = `-- name: DeleteResourceById :execresult
delete from resource where id = ?
`

func (q *Queries) DeleteResourceById(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteResourceById, id)
}

const deleteResourcesByIds = `-- name: DeleteResourcesByIds :execresult
delete from resource where id in (/*SLICE:ids*/?)
`

func (q *Queries) DeleteResourcesByIds(ctx context.Context, ids []string) (sql.Result, error) {
	query := deleteResourcesByIds
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	return q.db.ExecContext(ctx, query, queryParams...)
}

const insertResource = `-- name: InsertResource :exec
insert into resource (id, type, name, created_at, updated_at) values (?,?,?,?,?)
`

type InsertResourceParams struct {
	ID        string
	Type      string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertResource(ctx context.Context, arg InsertResourceParams) error {
	_, err := q.db.ExecContext(ctx, insertResource,
		arg.ID,
		arg.Type,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const selectResourceById = `-- name: SelectResourceById :one
select id, type, name, created_at, updated_at from resource where id = ?
`

func (q *Queries) SelectResourceById(ctx context.Context, id string) (Resource, error) {
	row := q.db.QueryRowContext(ctx, selectResourceById, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectResourcesByName = `-- name: SelectResourcesByName :many
select id, type, name, created_at, updated_at from resource where name like '%'||?1 ||'%'
`

func (q *Queries) SelectResourcesByName(ctx context.Context, name sql.NullString) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, selectResourcesByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResourceById = `-- name: UpdateResourceById :execresult
update resource set name = coalesce(?3,name), updated_at = ? where id = ?
`

type UpdateResourceByIdParams struct {
	Name      sql.NullString
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateResourceById(ctx context.Context, arg UpdateResourceByIdParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateResourceById, arg.Name, arg.UpdatedAt, arg.ID)
}
