// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as resource$0 from "../resource/models.js";

export interface CreateEntryReq {
    "Title": string;
    "Username": string;
    "Password": string;
    "URL": string;
    "Notes": string;
}

export interface Entry {
    "ID": string;
    "Kind": resource$0.Kind;
    "Path": string;
    "CreatedAt": string;
    "UpdatedAt": string;
    "Payload": Payload | null;
}

export interface GeneratePasswordReq {
    "Length": number;
    "Uppercase": boolean;
    "Lowercase": boolean;
    "Numbers": boolean;
    "Symbols": boolean;
}

export interface ListEntriesReq {
    "Cursor": string;
    "Size": number;
    "Host": string;
}

export interface Payload {
    "title": string;
    "username": string;
    "password": string;
    "url": string;
    "notes": string;
}
