// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CreateVaultReq {
  Title: string
  Username: string
  Password: string
  URL: string
  Notes: string
}
