// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as common$0 from "../common/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateEntry(req: $models.CreateEntryReq): $CancellablePromise<void> {
    return $Call.ByID(2224624140, req);
}

export function GeneratePassword(req: $models.GeneratePasswordReq): $CancellablePromise<string> {
    return $Call.ByID(247052522, req);
}

export function ListEntries(req: $models.ListEntriesReq): $CancellablePromise<common$0.PageResult<$models.Entry | null>> {
    return $Call.ByID(3615775484, req);
}
