services:
  traefik:
    image: docker.io/library/traefik:v3.7
    container_name: traefik
    restart: unless-stopped

    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80

    ports:
      - "80:80"
      - "127.0.0.1:8080:8080"

    networks:
      - evorsio-dev

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  evorsio-dev:
    name: evorsio-dev