// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as resource$0 from "../resource/models.js";

export interface Entry {
    "ID": string;
    "Kind": resource$0.Kind;
    "Path": string;
    "CreatedAt": string;
    "UpdatedAt": string;
    "Type": EntryType;
}

export enum EntryType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    File = "file",
    Folder = "folder",
};

export interface ListEntriesReq {
    "cursor": string;
    "limit": number;
    "Dir": string;
    "Name": string;
}
