// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as resource$0 from "../resource/models.js";

export class Entry {
    /**
     * Creates a new Entry instance.
     * @param {Partial<Entry>} [$$source = {}] - The source object to create the Entry.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("Kind" in $$source)) {
            /**
             * @member
             * @type {resource$0.Kind}
             */
            this["Kind"] = resource$0.Kind.$zero;
        }
        if (!("Path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Path"] = "";
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["CreatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["UpdatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("Type" in $$source)) {
            /**
             * @member
             * @type {EntryType}
             */
            this["Type"] = EntryType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Entry}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $Create.DateFromTime;
        const $$createField4_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("CreatedAt" in $$parsedSource) {
            $$parsedSource["CreatedAt"] = $$createField3_0($$parsedSource["CreatedAt"]);
        }
        if ("UpdatedAt" in $$parsedSource) {
            $$parsedSource["UpdatedAt"] = $$createField4_0($$parsedSource["UpdatedAt"]);
        }
        return new Entry(/** @type {Partial<Entry>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const EntryType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    File: "file",
    Folder: "folder",
};

export class ListEntriesReq {
    /**
     * Creates a new ListEntriesReq instance.
     * @param {Partial<ListEntriesReq>} [$$source = {}] - The source object to create the ListEntriesReq.
     */
    constructor($$source = {}) {
        if (!("cursor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cursor"] = "";
        }
        if (!("limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["limit"] = 0;
        }
        if (!("Dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Dir"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListEntriesReq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ListEntriesReq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListEntriesReq(/** @type {Partial<ListEntriesReq>} */($$parsedSource));
    }
}
