/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashRouteRouteImport } from './routes/dash/route'
import { Route as DashIndexRouteImport } from './routes/dash/index'
import { Route as DashDriveIndexRouteImport } from './routes/dash/drive/index'
import { Route as DashVaultIndexRouteImport } from './routes/dash/vault/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRouteRoute = DashRouteRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashDriveIndexRoute = DashDriveIndexRouteImport.update({
  id: '/drive/',
  path: '/drive/',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashVaultIndexRoute = DashVaultIndexRouteImport.update({
  id: '/vault/',
  path: '/vault/',
  getParentRoute: () => DashRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dash': typeof DashRouteRouteWithChildren
  '/dash/': typeof DashIndexRoute
  '/dash/drive/': typeof DashDriveIndexRoute
  '/dash/vault/': typeof DashVaultIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dash': typeof DashIndexRoute
  '/dash/drive': typeof DashDriveIndexRoute
  '/dash/vault': typeof DashVaultIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dash': typeof DashRouteRouteWithChildren
  '/dash/': typeof DashIndexRoute
  '/dash/drive/': typeof DashDriveIndexRoute
  '/dash/vault/': typeof DashVaultIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dash' | '/dash/' | '/dash/drive/' | '/dash/vault/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dash' | '/dash/drive' | '/dash/vault'
  id: '__root__' | '/' | '/dash' | '/dash/' | '/dash/drive/' | '/dash/vault/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRouteRoute: typeof DashRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/': {
      id: '/dash/'
      path: '/'
      fullPath: '/dash/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/dash/drive/': {
      id: '/dash/drive/'
      path: '/drive'
      fullPath: '/dash/drive/'
      preLoaderRoute: typeof DashDriveIndexRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/dash/vault/': {
      id: '/dash/vault/'
      path: '/vault'
      fullPath: '/dash/vault/'
      preLoaderRoute: typeof DashVaultIndexRouteImport
      parentRoute: typeof DashRouteRoute
    }
  }
}

interface DashRouteRouteChildren {
  DashIndexRoute: typeof DashIndexRoute
  DashDriveIndexRoute: typeof DashDriveIndexRoute
  DashVaultIndexRoute: typeof DashVaultIndexRoute
}

const DashRouteRouteChildren: DashRouteRouteChildren = {
  DashIndexRoute: DashIndexRoute,
  DashDriveIndexRoute: DashDriveIndexRoute,
  DashVaultIndexRoute: DashVaultIndexRoute,
}

const DashRouteRouteWithChildren = DashRouteRoute._addFileChildren(
  DashRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRouteRoute: DashRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
