services:
  redis:
    image: redis:7
    container_name: evorsio-cache
    restart: unless-stopped
    networks:
      - evorsio
    ports:
      - "6379:6379"

networks:
  evorsio:
    external: true