// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drive.sql

package db

import (
	"context"
)

const selectFileById = `-- name: SelectFileById :one
select
    r.id, r.type, r.name, r.created_at, r.updated_at,
    f.resource_id, f.size, f.mime_type
from file f
         join resource r
                    on r.id = f.resource_id
where r.id = ? and r.type = 'file'
`

type SelectFileByIdRow struct {
	Resource Resource
	File     File
}

func (q *Queries) SelectFileById(ctx context.Context, id string) (SelectFileByIdRow, error) {
	row := q.db.QueryRowContext(ctx, selectFileById, id)
	var i SelectFileByIdRow
	err := row.Scan(
		&i.Resource.ID,
		&i.Resource.Type,
		&i.Resource.Name,
		&i.Resource.CreatedAt,
		&i.Resource.UpdatedAt,
		&i.File.ResourceID,
		&i.File.Size,
		&i.File.MimeType,
	)
	return i, err
}

const selectFolderById = `-- name: SelectFolderById :one
select
    r.id, r.type, r.name, r.created_at, r.updated_at
from resource r where id = ? and type = 'folder'
`

type SelectFolderByIdRow struct {
	Resource Resource
}

func (q *Queries) SelectFolderById(ctx context.Context, id string) (SelectFolderByIdRow, error) {
	row := q.db.QueryRowContext(ctx, selectFolderById, id)
	var i SelectFolderByIdRow
	err := row.Scan(
		&i.Resource.ID,
		&i.Resource.Type,
		&i.Resource.Name,
		&i.Resource.CreatedAt,
		&i.Resource.UpdatedAt,
	)
	return i, err
}

const selectSymlinkById = `-- name: SelectSymlinkById :one
select
    r.id, r.type, r.name, r.created_at, r.updated_at,
    s.resource_id, s.target_id
from symlink s
         join resource r
                    on r.id = s.resource_id
where r.id = ? and r.type = 'symlink'
`

type SelectSymlinkByIdRow struct {
	Resource Resource
	Symlink  Symlink
}

func (q *Queries) SelectSymlinkById(ctx context.Context, id string) (SelectSymlinkByIdRow, error) {
	row := q.db.QueryRowContext(ctx, selectSymlinkById, id)
	var i SelectSymlinkByIdRow
	err := row.Scan(
		&i.Resource.ID,
		&i.Resource.Type,
		&i.Resource.Name,
		&i.Resource.CreatedAt,
		&i.Resource.UpdatedAt,
		&i.Symlink.ResourceID,
		&i.Symlink.TargetID,
	)
	return i, err
}
