// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Entry struct {
	ParentID string
	ChildID  string
}

type File struct {
	ResourceID string
	Size       int64
	MimeType   string
}

type Resource struct {
	ID        string
	Type      string
	Name      string
	CreatedAt string
	UpdatedAt string
}

type Symlink struct {
	ResourceID string
	TargetID   string
}
